### ISSUE TITLE
Incompatability with Strategia mod

### ISSUE THREAD

**Issue by kobe-maru** [Sigma88/Sigma-Binary#46]
Systems configured by sigma binary (Duna/Ike and Plock/Karen from OPM for me) end up loosing their manned and unmanned programs from the strategia mod by nightingale. It looks like this issue was addressed in the Strategia changelog about a year ago. Nightingale hasn't replied on the KSP forums though.

Logs 'n stuff: 

https://www.dropbox.com/s/o8ktbr5qid1mzxb/binary.zip?dl=0

**Comment by Sigma88** [comment]
are there any news from nightingale on this ? I have no idea what could be causing the issue

**Comment by kobe-maru** [comment]
Not yet, I posted in the thread again, hopefully I get a reply this time. I think it has to do with re-naming the parent body of the planetary system's as the bary-center...

**Comment by Sigma88** [comment]
I don't think there is anything I can do about this, sorry
