### ISSUE TITLE
Strange Blue Dot

### ISSUE THREAD

**Issue by FractalCyclone** [Sigma88/Sigma-Binary#52]
Blue Dot from Sigma Binary / Distant Object Enhancement conflict.

Spawns from craft, single-sided texture invisible when viewed from any other direction. Not collidable, static once spawned.

The issue only presents itself when there is a binary system loaded and Distant Object Enhancement is installed.

![screenshot2](https://user-images.githubusercontent.com/56998435/67609282-8b1f3280-f751-11e9-9c11-156f67603bc5.png)
![screenshot0](https://user-images.githubusercontent.com/56998435/67609283-8b1f3280-f751-11e9-89c7-3332cdb08aa9.png)

> KSP 1.7.3
Kopernicus - 1.7.3.2
ModularFlightIntegrator - 1.2.6.0
Sigma Binary - 1.7.2
Distant Object Enhancement - 1.9.1.1
SigmaDunaIke

[KSP.log](https://github.com/Sigma88/Sigma-Binary/files/3774110/KSP.log)

**Comment by Sigma88** [comment]
After looking at this issue I would say that most likely the dot is added by DOE

The issue might show up only on SB because my mod adds very tiny bodies, I am not sure how DOE works tho, it might be helpful to get @moardv opinion on this

**Comment by Sigma88** [comment]
I would also like to post this video that might give a better idea of the bug compared to screenshots

https://www.youtube.com/watch?v=uXpxmd7ZNNo

**Comment by MOARdV** [comment]
Some notes from after I responded to your (Sigma88)'s PM on the KSP forum:

Based on the NRE in the log and the presence of a body flare on-screen, it is most likely in the second foreach loop in FlareDraw::GenerateBodyFlares ( https://github.com/MOARdV/DistantObject/blob/6a6c58bd6da882e0d52f38305f0b6584c80c6bbb/Source-Code/FlareDraw.cs#L283-L331 ).

I'm not sure what in that code would be coming up null, but I'm also not familiar with what's going on under the hood in Sigma Binary.  As I mentioned in the DOE issue, I don't have the time to maintain DOE, so I'm not going to be able to resolve the issue any time soon.

**Comment by Sigma88** [comment]
@moardv do you mind if I try to fix the issue and send you a PR? I think I might have an idea on how to approach this

**Comment by Sigma88** [comment]
@FractalCyclone  would you mind testing this ALPHA version of DOE and let me know if it works fine?
[DistantObject_1.9.1.1_ALPHA.zip](https://github.com/Sigma88/Sigma-Binary/files/3780902/DistantObject_1.9.1.1_ALPHA.zip)

thanks!

**Comment by FractalCyclone** [comment]
@Sigma88 

I tried the alpha version of DOE with the same set of mods as before and it still resulted in the blue circle.

Sorry for the late response, work kick'd my butt last couple days.

> KSP 1.7.3
Kopernicus - 1.7.3.2
ModularFlightIntegrator - 1.2.6.0
Sigma Binary - 1.7.2
Distant Object Enhancement - 1.9.1.1_ALPHA
SigmaDunaIke

![screenshot10](https://user-images.githubusercontent.com/56998435/67918457-64eefd80-fb6a-11e9-9a0d-91cf90769465.png)

[KSP.log](https://github.com/Sigma88/Sigma-Binary/files/3792128/KSP.log)

**Comment by Sigma88** [comment]
that's weird, I didn't get the NullRef you are getting

I wonder if I included the wrong dll in the archive, let me check again

**Comment by Sigma88** [comment]
yeah, it seems the wrong dll got included in the archive -.-

sorry

here's the fixed dll
[DistantObject_1.9.1.1_ALPHA2.zip](https://github.com/Sigma88/Sigma-Binary/files/3793229/DistantObject_1.9.1.1_ALPHA2.zip)

**Comment by Sigma88** [comment]
as soon as I get the OK from you I will release DOE 1.9.1.2

**Comment by Sigma88** [comment]
I decided to go ahead and release the fix here:
https://github.com/Sigma88/DistantObject/releases

if you have other issues please open them here:
https://github.com/Sigma88/DistantObject/issues
