### ISSUE TITLE
Blue dot 

### ISSUE THREAD

**Issue by Spike8891** [Sigma88/Sigma-Binary#54]
I’m encountering the issue between Sigma Binary and Distant Object Enhancement detailed here:  https://github.com/Sigma88/Sigma-Binary/issues/52

I see you resolved the issue with a DoE patch, however when DoE was taken over by The Dark Badger, it looks like he took over the version prior to your patch. I’ve reached out to him on the forums to see if he could take a look at it, but I am waiting for a reply. Is it possible for you to detail the fix you did to DoE? Can it simply be fixed with a patch?

**Comment by Sigma88** [comment]
hi there, to be completely honest I have very little memory about this.

however from my released DOE version the fix looks pretty simple:
https://github.com/Sigma88/DistantObject/commit/7e4da791a9daba07d5fbb593b59aa117f063a248

I'll see if I can make a PR for TDB

**Comment by Spike8891** [comment]
How would I go about compiling this fix on my own while waiting for The Dark badger to fix it? I understand the process of forking the project, and making your change, but don't know where to go from there.

**Comment by Sigma88** [comment]
you would have to get a compiler like visual studio and compile the code into a dll.

if you never did anything like this, it will take a while to get the hang of things.

you are probably better off just waiting for @TheDarkBadger to release an update

**Comment by Spike8891** [comment]
Latest update of Distant Object Enhancement fixed the issue.
